services:
    redis:
        image: redis
        container_name: Redis
        ports:
        - "6379:6379"

    appcontainer:
        image: ${DOCKER_REGISTRY-}appcontainer
        ports:
          - "5001:5001"
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=https://+:5001/
        build:
            context: .
            dockerfile: AppContainer/Dockerfile



